GroomingSalon/GroomingSalon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Salon.views import main

urlpatterns = [
    path('', include('Salon.urls')),
    path('admin/', admin.site.urls),
    path('salon/', main),
    path('account/', include('Users.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GroomingSalon/Salon/urls.py
from django.urls import path
from . import views
from Users import views as user_views


urlpatterns = [
    path('', views.main, name="home"),
    path('services', views.services, name="services"),
    path('lk', views.lk, name="lk"),
    path('archive_lk', views.archive_lk, name="archive_lk"),
    path('portfolio/<int:master_id>', views.portfolio, name="portfolio"),
    path('groomers', views.groomers, name="groomers"),
    path('administration', views.administration, name="administration"),
    path('archive_admin', views.archive_admin, name="archive_admin"),
    path('create-groomer', views.create_groomer, name="create_groomer"),
    path('create-serv', views.create_serv, name="create_serv"),
    path('record/<int:pet_id>', views.record, name="record"),
    path('reg-pet', views.reg_pet, name="reg-pet"),
    path('admin_status/<int:rec_id>', views.admin_status, name="admin_status"),
    path('admin-groomers', views.admin_groomers, name="admin_groomers"),
    path('admin-services', views.admin_services, name="admin_services"),
    path('admin-clients', views.admin_clients, name="admin_clients"),
    path('admin-client-pets/<int:client_id>', views.admin_client_pets, name="admin_client_pets"),
    path('admin-change-pet-inf/<int:pet_id>', views.admin_change_pet_inf, name="admin_change_pet_inf"),
    path('admin-reg-pet/<int:client_id>', views.admin_reg_pet, name="admin_reg_pet"),
    path('admin-record/<int:pet_id>/<int:client_id>', views.admin_record, name="admin_record"),
    path('change-pet-inf/<int:pet_id>', views.change_pet_inf, name="change-pet-inf"),
    path('change-service/<int:serv_id>', views.change_service, name="change-service"),
    path('change-groomer/<int:groomer_id>', views.change_groomer, name="change-groomer"),
    path('ajax/load-time/', views.load_time, name='ajax-load-time'),
    path('ajax/load-time-master/', views.load_time_master, name='ajax-load-time-master'),
    path('ajax/load-race/', views.load_race, name='ajax-load-race'),
]

GroomingSalon/Salon/models.py
from django.db import models
from Users.models import *

# Create your models here.
CHOISE_TIME = {
    "09:00": "09:00",
    "10:00": "10:00",
    "11:00": "11:00",
    "12:00": "12:00",
    "13:00": "13:00",
    "14:00": "14:00",
    "15:00": "15:00",
    "16:00": "16:00",
    "17:00": "17:00",
}

STATUS_CHOISE = {
    "1": "Ожидание подтверждения",
    "2": "Запись подтверждена",
    "3": "Выполнена",
    "4": "Отменена",
}


class TypeAnimal(models.Model):
    type = models.CharField(max_length=15, default="Собака")

    def __str__(self):
        return self.type

    class Meta:
        verbose_name = "Тип"
        verbose_name_plural = "Типы"


class Race(models.Model):
    name_race = models.CharField(max_length=100)
    type = models.ForeignKey(TypeAnimal, on_delete=models.CASCADE, default=1, blank=True)

    def __str__(self):
        return self.name_race

    class Meta:
        verbose_name = "Порода"
        verbose_name_plural = "Породы"


class Pet(models.Model):
    name = models.CharField(max_length=50)
    race = models.ForeignKey(Race, on_delete=models.CASCADE)
    age = models.PositiveIntegerField()
    type = models.ForeignKey(TypeAnimal, on_delete=models.CASCADE)
    photo = models.ImageField(default="", blank=True, upload_to="pets")

    def __str__(self):
        return self.race.name_race + " " + self.name

    class Meta:
        verbose_name = "Питомец"
        verbose_name_plural = "Питомцы"


class Service(models.Model):
    name = models.CharField(max_length=100)
    price = models.PositiveIntegerField()
    description = models.TextField(max_length=1000)
    type = models.ForeignKey(TypeAnimal, on_delete=models.CASCADE)

    def __str__(self):
        return self.name + " " + str(self.price)+"р"

    class Meta:
        verbose_name = "Услуга"
        verbose_name_plural = "Услуги"


class Employee(models.Model):
    fam = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    otch = models.CharField(max_length=50)
    exp = models.CharField(max_length=50)
    photo = models.ImageField(default="", blank=True, upload_to="groomers")
    about = models.TextField(default="", blank=True, max_length=1000)

    def __str__(self):
        return self.fam + " " + self.name + " " + self.otch

    class Meta:
        verbose_name = "Грумер"
        verbose_name_plural = "Грумеры"


class Portfolio(models.Model):
    employee = models.ForeignKey(Employee, default="1", related_name="employee", on_delete=models.CASCADE)
    photo = models.ImageField(default="")
    description = models.TextField(max_length=250)

    def __str__(self):
        return self.employee.fam + " " + self.employee.name + " " + self.description

    class Meta:
        verbose_name = "Портфолио"
        verbose_name_plural = "Портфолио"


class PetAndUser(models.Model):
    pet = models.ForeignKey(Pet, default="1", related_name="pet", on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, default="1", related_name="user", on_delete=models.CASCADE)

    def __str__(self):
        return self.user.surname + " - " + self.pet.name

    class Meta:
        verbose_name = "Клиент и питомец"
        verbose_name_plural = "Клиенты и питомцы"


class Record(models.Model):
    pet_user = models.ForeignKey(PetAndUser, default="1", on_delete=models.CASCADE)
    master = models.ForeignKey(Employee, default="1", on_delete=models.CASCADE)
    time = models.CharField(max_length=50, choices=CHOISE_TIME)
    date = models.DateField()
    service = models.ForeignKey(Service, default="1", on_delete=models.CASCADE)
    status = models.CharField(max_length=50, choices=STATUS_CHOISE)

    class Meta:
        verbose_name = "Запись"
        verbose_name_plural = "Записи"

GroomingSalon/Salon/views.py
import json

from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from Users.models import CustomUser
from Salon.models import Service
from Salon.forms import *
from Users.models import *


CHOISE_TIME = {
    "09:00": "09:00",
    "10:00": "10:00",
    "11:00": "11:00",
    "12:00": "12:00",
    "13:00": "13:00",
    "14:00": "14:00",
    "15:00": "15:00",
    "16:00": "16:00",
    "17:00": "17:00",
}


def main(request):
    return render(request, 'Salon/Main.html')


def services(request):
    user_profile = None
    if request.user.is_authenticated:
        user_profile = CustomUser.objects.get(phone_number=request.user.phone_number)
    query = request.GET.get('search')
    if query is None:
        services = Service.objects.all()
    else:
        services = Service.objects.filter(Q(name__iregex=query) | Q(price__icontains=query) | Q(description__iregex=query))
    return render(request, 'Salon/Services.html', {'services': services, 'user_profile': user_profile})


def lk(request):
    user_profile = None
    if request.user.is_authenticated:
        user_profile = CustomUser.objects.get(phone_number=request.user.phone_number)
    pets = PetAndUser.objects.filter(user=request.user)
    records = Record.objects.filter(pet_user__user=request.user).exclude(status=3).order_by("-date", "time")
    context = {'user_profile': user_profile, 'pets': pets, 'records': records}
    if request.user.is_superuser:
        return redirect('administration')
    return render(request, 'Salon/LK.html', context)


def archive_lk(request):
    user_profile = request.user
    records = Record.objects.filter(pet_user__user=request.user).order_by("-date", "time")
    context = {'user_profile': user_profile, 'records': records}
    return render(request, 'Salon/Archive.html', context)


def portfolio(request, master_id):
    master = Employee.objects.get(id=master_id)
    portfolios = Portfolio.objects.filter(employee=master)

    context = {'master': master, 'portfolios': portfolios}

    return render(request, 'Salon/Portfolio.html', context)


def reg_pet(request):
    form = RegPetForm(request.POST)
    form.fields['race'].queryset = Race.objects.order_by("name_race")
    if request.method == 'POST':
        form = RegPetForm(request.POST, request.FILES)
        if form.is_valid():
            name = form.cleaned_data['name']
            race = form.cleaned_data['race']
            age = form.cleaned_data['age']
            photo = form.cleaned_data['photo']
            type = form.cleaned_data['type']
            pet = Pet.objects.create(
                name=name,
                race=race,
                age=age,
                type=type,
                photo=photo)
            user = CustomUser.objects.get(phone_number=request.user.phone_number)
            pet_user = PetAndUser.objects.create(pet=pet, user=user)
            pet_user.save()
            return render(request, 'Salon/Reg-pet-ready.html')
    return render(request, 'Salon/Reg-pet.html', {'form': form})


def load_race(request):
    type_id = request.GET.get('type_id')
    races = Race.objects.filter(type=type_id).order_by("name_race")
    return render(request, 'Salon/ajax-race.html', {'races': races})


# Администрирование >

def administration(request):
    records = Record.objects.all().exclude(status=3).order_by("-date", "time")
    query = request.GET.get('search')
    date = request.GET.get('date')
    if query or date is not None:
        if query is not None:
            records = records.filter(
                Q(pet_user__user__surname__iregex=query) | Q(pet_user__user__name__iregex=query) |
                Q(pet_user__user__phone_number__iregex=query) | Q(pet_user__pet__name__iregex=query) |
                Q(service__name__iregex=query) | Q(master__fam__iregex=query) |
                Q(master__name__iregex=query) | Q(master__otch__iregex=query)).order_by("-date", "time")
        if date is not None:
            if date == "increasing":
                records = records.order_by("-id", "-date", "time")
            else:
                records = records.order_by("id", "date", "time")
        if query and date is not None:
            records = records.filter(
                Q(pet_user__user__surname__iregex=query) | Q(pet_user__user__name__iregex=query) |
                Q(pet_user__user__phone_number__iregex=query) | Q(pet_user__pet__name__iregex=query) |
                Q(service__name__iregex=query) | Q(master__fam__iregex=query) |
                Q(master__name__iregex=query) | Q(master__otch__iregex=query))
            if date == "increasing":
                records = records.order_by("-date", "time")
            else:
                records = records.order_by("date", "time")
    return render(request, 'Salon/Administration.html', {'records': records})


def archive_admin(request):
    records = Record.objects.filter(status=3).order_by("-date", "time")
    context = {'records': records}
    return render(request, 'Salon/Archive_admin.html', context)


def create_groomer(request):
    form = CreateGroomer(request.POST)
    if request.method == 'POST':
        form = CreateGroomer(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return render(request, 'Salon/Groomer-ready.html')
    return render(request, 'Salon/Create-groomer.html', {'form': form})


def create_serv(request):
    form = CreateServ(request.POST)
    if request.method == 'POST':
        form = CreateServ(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'Salon/Serv-ready.html')
    return render(request, 'Salon/Create-serv.html', {'form': form})


def admin_status(request, rec_id):
    rec = Record.objects.get(id=rec_id)
    form = RecordChangeStatus
    if request.method == "POST":
        form = RecordChangeStatus(request.POST, instance=rec)
        if form.is_valid():
            form.save()
            return redirect('administration')
    return render(request, 'Salon/Admin-status.html', {'form': form})


def admin_services(request):
    user_profile = None
    if request.user.is_authenticated:
        user_profile = CustomUser.objects.get(phone_number=request.user.phone_number)
    query = request.GET.get('search')
    if query is None:
        services = Service.objects.all()
    else:
        services = Service.objects.filter(Q(name__iregex=query) | Q(price__icontains=query) | Q(description__iregex=query))
    return render(request, 'Salon/Admin-services.html', {'services': services, 'user_profile': user_profile})


def change_service(request, serv_id):
    serv = Service.objects.get(id=serv_id)
    if request.method == 'POST':
        form = ChangeServ(request.POST, instance=serv)
        if form.is_valid():
            form.save()
            return redirect('admin_services')
    else:
        form = ChangeServ(instance=serv)
    return render(request, 'Salon/Change-serv-inf.html', {'form': form})


def admin_groomers(request):
    query = request.GET.get('search')
    if query is None:
        groomer = Employee.objects.all()
    else:
        groomer = Employee.objects.filter(
            Q(fam__iregex=query) | Q(name__iregex=query) | Q(otch__iregex=query))
    context = {'groomer': groomer}
    return render(request, 'Salon/Admin-groomers.html', context)


def change_groomer(request, groomer_id):
    groomer = Employee.objects.get(id=groomer_id)
    if request.method == 'POST':
        form = ChangeGroomer(request.POST, instance=groomer)
        if form.is_valid():
            form.save()
            return redirect('groomers')
    else:
        form = ChangeGroomer(instance=groomer)
    return render(request, 'Salon/Change-groomer-inf.html', {'form': form})


def admin_clients(request):
    query = request.GET.get('search')
    if query is None:
        clients = CustomUser.objects.all()
    else:
        clients = CustomUser.objects.filter(
            Q(phone_number__iregex=query) | Q(surname__iregex=query) | Q(name__iregex=query))
    context = {'clients': clients}
    return render(request, 'Salon/Admin-clients.html', context)


def admin_client_pets(request, client_id):
    client = CustomUser.objects.get(id=client_id)
    pets = PetAndUser.objects.filter(user=client)
    context = {'client': client, 'pets': pets}
    return render(request, 'Salon/Client-pets.html', context)


def admin_change_pet_inf(request, pet_id):
    pet = Pet.objects.get(id=pet_id)
    client_pet = PetAndUser.objects.get(pet=pet)
    client = CustomUser.objects.get(phone_number=client_pet.user.phone_number)
    if request.method == 'POST':
        form = PetChangeInf(request.POST, request.FILES, instance=pet)
        if form.is_valid():
            form.save()
            return redirect('admin_client_pets', client_id=client.id)
    else:
        form = PetChangeInf(instance=pet)
    return render(request, 'Salon/Change-pet-inf.html', {'form': form})


def admin_reg_pet(request, client_id):
    form = RegPetForm(request.POST)
    form.fields['race'].queryset = Race.objects.order_by("name_race")
    if request.method == 'POST':
        form = RegPetForm(request.POST, request.FILES)
        if form.is_valid():
            name = form.cleaned_data['name']
            race = form.cleaned_data['race']
            age = form.cleaned_data['age']
            photo = form.cleaned_data['photo']
            type = form.cleaned_data['type']
            pet = Pet.objects.create(
                name=name,
                race=race,
                age=age,
                type=type,
                photo=photo)
            user = CustomUser.objects.get(id=client_id)
            pet_user = PetAndUser.objects.create(pet=pet, user=user)
            pet_user.save()
            return redirect('admin_client_pets', client_id=client_id)
    return render(request, 'Salon/Reg-pet.html', {'form': form})

GroomingSalon/Salon/templates/Salon/Administration.html
{% extends 'Salon/Layout.html' %}
{% load static %}
{% load humanize %}

{% block title %}
Администрирование | Груминг салон для животных "Опрятные лапки" - стрижка собак и кошек
{% endblock %}

{% block content %}
<div class="profile-main">
    <h1 style="text-align:center;">Администрирование</h1>
    <hr color="#de8b37" size="1px" width="100%"/>
        <div class="admin-btn">
            <a href="{% url 'admin_clients' %}"><button class="btn-reg_log">Клиенты</button></a>
            <a href="{% url 'admin_services' %}"><button class="btn-reg_log">Услуги</button></a>
            <a href="{% url 'admin_groomers' %}"><button class="btn-reg_log">Грумеры</button></a>
            <a href="{% url 'archive_admin' %}"><button class="btn-reg_log">Архив записей</button></a>
            <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn-reg_log" style="margin:20px 0 0 0; width:400px;">Выйти из режима администирования</button>
            </form>
        </div>
    <hr color="#de8b37" size="1px" width="100%"/>
    <div class="head-adm">
        <div class="search-rec-adm">
            <form action="{% url 'administration' %}" method="get" class="search-rec-adm-input">
                <h1 class="name-service-part" style="width: 300px; font-size:30px; margin:auto;">Записи на прием</h1>
                <input name="search" type="text" placeholder="Поиск..." style="width: 300px; margin:10px">
                <div style="width: 200px; margin: auto 20;">
                    Сортировка по дате:
                        <label class="radio-btn" for="inc"><input id="inc" value="increasing" name="date" type="radio" style="width: 50px" placeholder="yyyy-mm-dd (DOB)" >от новых к старым</label>
                        <label class="radio-btn" for="dec"><input id="dec" value="decreasing" name="date" type="radio" style="width: 50px" placeholder="yyyy-mm-dd (DOB)"> от старых к новым </label>
                </div>
                <button type="submit" >Найти</button>
            </form>
        </div>
    </div>
            <hr color="#de8b37" size="1px" width="100%"/>
    <div class="profile-inner">
                 {% if records %}
                {% for rec in records %}
                <div class="record" style="margin: 0; padding: 10 10 10 10;">
                    {% if rec.status == "1" %}
                    <h4><i class='fa fa-exclamation-circle' style='color:#fa5b2a'></i> Запись № {{ rec.id }}  -  Ожидание подтверждения</h4>
                    {% elif rec.status == "2" %}
                    <h4><i class='fa fa-exclamation-circle' style='color:#faa72a'></i> Запись № {{ rec.id }}  -  Запись подтверждена</h4>
                    {% elif rec.status == "3" %}
                    <h4><i class='bi bi-check-circle-fill' style='color:#16f296'></i> Запись № {{ rec.id }}  -  Выполнена</h4>
                    {% endif %}
                    <hr color="#de8b37" size="1px" width="95%"/>
                    <p>Дата: {{ rec.date }}  Время: {{ rec.time }}</p>
                    <p>Клиент: {% if rec.pet_user.user.surname %}{{ rec.pet_user.user.surname }} {{ rec.pet_user.user.name }}, {{ rec.pet_user.user.phone_number }}{% else %} {{ rec.pet_user.user.phone_number }}{% endif %}</p>
                    <p>Питомец: {{ rec.pet_user.pet.name }}</p>
                    <p>Услуга: {{ rec.service.name }}, стоимость: {{ rec.service.price|intcomma }}р.</p>
                    <p>Грумер: {{ rec.master.fam }} {{rec.master.name}} {{rec.master.otch}}</p>
                    <hr color="#de8b37" size="1px" width="95%"/>
                    {% if not rec.status == "3" %}
                    <a href="{% url 'admin_status' rec.id %}"><button class="btn-reg_log" style="margin:0">Изменить статус заявки</button></a>
                    {% endif %}
                </div>
                {% endfor %}
                {% endif %}

    </div>

</div>
{% endblock %}

GroomingSalon/Salon/templates/Salon/Archive.html
{% extends 'Salon/Layout.html' %}
{% load static %}
{% load humanize %}

{% block title %}
Архив записей на прием | Груминг салон для животных "Опрятные лапки" - стрижка собак и кошек
{% endblock %}

{% block content %}
<div class="profile-main">
    <div class="head-archive">
        <a href="javascript:history.back()" style="text-decoration:none; color:black; margin: 10px 0 0 40px;"><i class="bi bi-caret-left" style=" font-size: 50px;"></i></a>
        <h1 style="text-align:center;">Архив записей на прием</h1>
    </div>


    <hr color="#de8b37" size="5px" width="100%"/>
    <div class="profile-inner">
                {% if records %}
                {% for rec in records %}
                <div class="record" style="margin: 0; padding: 10 10 10 10;">
                    <h4>Запись № {{ rec.id }}  -  {% if rec.status == "1" %} Ожидание подтверждения {% elif rec.status == "2" %} Запись подтверждена {% elif rec.status == "3" %} Выполнена {% endif %}</h4>
                    <hr color="#de8b37" size="5px" width="95%"/>
                    <p>Дата: {{ rec.date }}  Время: {{ rec.time }}</p>
                    <p>Питомец: {{ rec.pet_user.pet.name }}</p>
                    <p>Услуга: {{ rec.service.name }}, стоимость: {{ rec.service.price|intcomma }}р.</p>
                    <p>Грумер: {{ rec.master.fam }} {{rec.master.name}} {{rec.master.otch}}</p>
                    <hr color="#de8b37" size="5px" width="95%"/>
                </div>
                {% endfor %}
                {% endif %}
    </div>
</div>


{% endblock %}

GroomingSalon/Salon/templates/Salon/Archive_admin.html
{% extends 'Salon/Layout.html' %}
{% load static %}
{% load humanize %}

{% block title %}
Архив выполненых записей на прием | Груминг салон для животных "Опрятные лапки" - стрижка собак и кошек
{% endblock %}

{% block content %}
<div class="profile-main">
    <div class="head-archive">
        <a href="javascript:history.back()" style="text-decoration:none; color:black;"><i class="bi bi-caret-left" style=" font-size: 50px;"></i></a>
        <h1 style="text-align:center; margin:0;">Архив выполненых записей на прием</h1>
    </div>
    <hr color="#de8b37" size="5px" width="100%"/>
    <div class="profile-inner">
                {% if records %}
                {% for rec in records %}
                <div class="record" style="margin: 0; padding: 10 10 10 10;">
                    <h4><i class='bi bi-check-circle-fill' style='color:#16f296'></i>Запись № {{ rec.id }}  -  Выполнена</h4>
                    <hr color="#de8b37" size="5px" width="95%"/>
                    <p>Клиент: {% if rec.pet_user.user.surname %}{{ rec.pet_user.user.surname }} {{ rec.pet_user.user.name }}, {{ rec.pet_user.user.phone_number }}{% else %} {{ rec.pet_user.user.phone_number }}{% endif %}</p>
                    <p>Дата: {{ rec.date }}  Время: {{ rec.time }}</p>
                    <p>Питомец: {{ rec.pet_user.pet.name }}</p>
                    <p>Услуга: {{ rec.service.name }}, стоимость: {{ rec.service.price|intcomma }}р.</p>
                    <p>Грумер: {{ rec.master.fam }} {{rec.master.name}} {{rec.master.otch}}</p>
                    <hr color="#de8b37" size="5px" width="95%"/>
                </div>
                {% endfor %}
                {% endif %}
    </div>
</div>
{% endblock %}

GroomingSalon/Salon/templates/Salon/Bottom.html
{% load static %}
	<div class="footer__redes">
		<ul class="footer__redes-wrapper">
			<li>
				<a href="{% url 'home' %}" class="underline-one" style="text-decorations:none; color:white;">
					<i class="fab fa-vk"></i>
					вконтакте
				</a>
			</li>

			<li>
				<a href="{% url 'home' %}" class="underline-one" style="text-decorations:none; color:white;">
					<i class="bi bi-telegram"></i>
					telegram
				</a>
			</li>
			<li>
				<a href="{% url 'home' %}" class="underline-one" style="text-decorations:none; color:white;">
					<i class='fa fa-phone'></i>
					Контактный номер: +7 (985) 456-25-36
				</a>
			</li>
		</ul>
	</div>

GroomingSalon/Salon/templates/Salon/Change-serv-inf.html
{% extends 'Salon/Layout.html' %}
{% load static %}


{% block title %}
Форма редактирования услуг | Груминг салон для животных "Опрятные лапки" - стрижка собак и кошек
{% endblock %}

{% block content %}
<div class="reg-pet">
<h3>Редактирование услуги</h3>
<form class="form_add" method="post">
    {% csrf_token %}
    {{ form.name }}<br>
    {{ form.price }}<br>
    {{ form.description }}<br>
    {{ form.type }}<br>
    <span>{{ error }}</span>
    <p></p>
    <button class="btn-reg_log" type="submit">Сохранить</button>
</form>
</div>
{% endblock %}

GroomingSalon/Salon/templates/Salon/Create-serv.html
{% extends 'Salon/Layout.html' %}
{% load static %}


{% block title %}
Добавление услуг | Груминг салон для животных "Опрятные лапки" - стрижка собак и кошек
{% endblock %}

{% block content %}
<div class="reg-pet">
<h3>Добавление услуги</h3>

<form class="form_add" method="post">
    <div class="form_add_pet">
        {% csrf_token %}
        {{ form.name }}<br>
        {{ form.price }}<br>
        {{ form.description }}<br>
        {{ form.type }}<br>
    <span>{{ error }}</span>
        <p></p>
    </div>
    <button class="btn-reg_log" type="submit">Добавить</button>

</form>
</div>


{% endblock %}

GroomingSalon/Salon/templates/Salon/Groomer-ready.html
{% extends 'Salon/Layout.html' %}
{% load static %}


{% block title %}
Регистрация грумера | Груминг салон для животных "Опрятные лапки" - стрижка собак и кошек
{% endblock %}

{% block content %}
<div class="rec-pet-ready">
<h3>Регистрация грумера</h3>
<p>Регистрация грумера прошла успешно!</p>
</div>
{% endblock %}

GroomingSalon/Salon/templates/Salon/Record-ready.html
{% extends 'Salon/Layout.html' %}
{% load static %}


{% block title %}
Запись на прием | Груминг салон для животных "Опрятные лапки" - стрижка собак и кошек
{% endblock %}

{% block content %}
<div class="rec-pet-ready">
<h3>Запись на прием</h3>
<p>Запись питомца на прием прошла успешно!</p>
</div>
{% endblock %}

GroomingSalon/Salon/templates/Salon/Reg-pet-ready.html
{% extends 'Salon/Layout.html' %}
{% load static %}


{% block title %}
Регистрация питомца | Груминг салон для животных "Опрятные лапки" - стрижка собак и кошек
{% endblock %}

{% block content %}
<div class="rec-pet-ready">
<h3>Регистрация питомца</h3>
<p>Регистрация питомца прошла успешно!</p>
</div>
{% endblock %}

GroomingSalon/Salon/templates/Salon/Reg-pet.html
{% extends 'Salon/Layout.html' %}
{% load static %}


{% block title %}
Регистрация питомца | Груминг салон для животных "Опрятные лапки" - стрижка собак и кошек
{% endblock %}

{% block content %}
<div class="reg-pet">
<h3>Регистрация питомца</h3>

<form class="form_add" id="regPetForm" enctype="multipart/form-data" method="post" data-race-pet-url="{% url 'ajax-load-race' %}">
    <div class="form_add_pet">
        {% csrf_token %}
        {{ form.name }}<br>
        {{ form.type }}<br>
        {{ form.race }}<br>
        {{ form.age }}<br>
        {{ form.photo }}<br>
    <span>{{ error }}</span>
        <p></p>
    </div>
    <button class="btn-reg_log" type="submit">Сохранить</button>

</form>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_type").change(function () {
        const url = $("#regPetForm").attr("data-race-pet-url");
        const typeId = $(this).val();

        $.ajax({
            url: '{% url 'ajax-load-race' %}',
            data: {
                type_id: typeId
            },
            success: function (data) {
                $("#id_race").html(data);
            }
        });
    });
</script>


</div>


{% endblock %}

GroomingSalon/Salon/templates/Salon/ajax-race.html
<option value="">---------</option>
{% for race in races %}
<option value="{{ race.id }}">{{ race.name_race }}</option>
{% endfor %}